// tlswrapper (c) 2021-2026 He Xian <hexian000@outlook.com>
// This code is licensed under MIT license (see LICENSE for details)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: mux.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chunk carries payload bytes for a logical stream (one gRPC Stream RPC).
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_mux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_mux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_mux_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ClientHello is sent by the client as the first message on the Control stream.
type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	RejectInbound bool                   `protobuf:"varint,2,opt,name=reject_inbound,json=rejectInbound,proto3" json:"reject_inbound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_mux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_mux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_mux_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ClientHello) GetRejectInbound() bool {
	if x != nil {
		return x.RejectInbound
	}
	return false
}

// ServerHello is sent by the server in response to ClientHello on the Control stream.
type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	RejectInbound bool                   `protobuf:"varint,2,opt,name=reject_inbound,json=rejectInbound,proto3" json:"reject_inbound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_mux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_mux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_mux_proto_rawDescGZIP(), []int{2}
}

func (x *ServerHello) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ServerHello) GetRejectInbound() bool {
	if x != nil {
		return x.RejectInbound
	}
	return false
}

// OpenRequest is sent by the server on the Control stream to ask the client to
// open a new Stream RPC back to the server. The client identifies the resulting
// Stream RPC by setting x-mux-request-id in the outgoing gRPC metadata to
// request_id.
type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_mux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_mux_proto_rawDescGZIP(), []int{3}
}

func (x *OpenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// ControlMessage is the envelope for all messages on the Control stream.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControlMessage_ClientHello
	//	*ControlMessage_ServerHello
	//	*ControlMessage_OpenRequest
	Body          isControlMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_mux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_mux_proto_rawDescGZIP(), []int{4}
}

func (x *ControlMessage) GetBody() isControlMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlMessage) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *ControlMessage) GetServerHello() *ServerHello {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ServerHello); ok {
			return x.ServerHello
		}
	}
	return nil
}

func (x *ControlMessage) GetOpenRequest() *OpenRequest {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_OpenRequest); ok {
			return x.OpenRequest
		}
	}
	return nil
}

type isControlMessage_Body interface {
	isControlMessage_Body()
}

type ControlMessage_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,1,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type ControlMessage_ServerHello struct {
	ServerHello *ServerHello `protobuf:"bytes,2,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type ControlMessage_OpenRequest struct {
	OpenRequest *OpenRequest `protobuf:"bytes,3,opt,name=open_request,json=openRequest,proto3,oneof"`
}

func (*ControlMessage_ClientHello) isControlMessage_Body() {}

func (*ControlMessage_ServerHello) isControlMessage_Body() {}

func (*ControlMessage_OpenRequest) isControlMessage_Body() {}

var File_mux_proto protoreflect.FileDescriptor

const file_mux_proto_rawDesc = "" +
	"\n" +
	"\tmux.proto\x12\x11tlswrapper.mux.v1\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"P\n" +
	"\vClientHello\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12%\n" +
	"\x0ereject_inbound\x18\x02 \x01(\bR\rrejectInbound\"P\n" +
	"\vServerHello\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12%\n" +
	"\x0ereject_inbound\x18\x02 \x01(\bR\rrejectInbound\",\n" +
	"\vOpenRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xe7\x01\n" +
	"\x0eControlMessage\x12C\n" +
	"\fclient_hello\x18\x01 \x01(\v2\x1e.tlswrapper.mux.v1.ClientHelloH\x00R\vclientHello\x12C\n" +
	"\fserver_hello\x18\x02 \x01(\v2\x1e.tlswrapper.mux.v1.ServerHelloH\x00R\vserverHello\x12C\n" +
	"\fopen_request\x18\x03 \x01(\v2\x1e.tlswrapper.mux.v1.OpenRequestH\x00R\vopenRequestB\x06\n" +
	"\x04body2\x9c\x01\n" +
	"\x03Mux\x12S\n" +
	"\aControl\x12!.tlswrapper.mux.v1.ControlMessage\x1a!.tlswrapper.mux.v1.ControlMessage(\x010\x01\x12@\n" +
	"\x06Stream\x12\x18.tlswrapper.mux.v1.Chunk\x1a\x18.tlswrapper.mux.v1.Chunk(\x010\x01B.Z,github.com/hexian000/tlswrapper/v4/mux/protob\x06proto3"

var (
	file_mux_proto_rawDescOnce sync.Once
	file_mux_proto_rawDescData []byte
)

func file_mux_proto_rawDescGZIP() []byte {
	file_mux_proto_rawDescOnce.Do(func() {
		file_mux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mux_proto_rawDesc), len(file_mux_proto_rawDesc)))
	})
	return file_mux_proto_rawDescData
}

var file_mux_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mux_proto_goTypes = []any{
	(*Chunk)(nil),          // 0: tlswrapper.mux.v1.Chunk
	(*ClientHello)(nil),    // 1: tlswrapper.mux.v1.ClientHello
	(*ServerHello)(nil),    // 2: tlswrapper.mux.v1.ServerHello
	(*OpenRequest)(nil),    // 3: tlswrapper.mux.v1.OpenRequest
	(*ControlMessage)(nil), // 4: tlswrapper.mux.v1.ControlMessage
}
var file_mux_proto_depIdxs = []int32{
	1, // 0: tlswrapper.mux.v1.ControlMessage.client_hello:type_name -> tlswrapper.mux.v1.ClientHello
	2, // 1: tlswrapper.mux.v1.ControlMessage.server_hello:type_name -> tlswrapper.mux.v1.ServerHello
	3, // 2: tlswrapper.mux.v1.ControlMessage.open_request:type_name -> tlswrapper.mux.v1.OpenRequest
	4, // 3: tlswrapper.mux.v1.Mux.Control:input_type -> tlswrapper.mux.v1.ControlMessage
	0, // 4: tlswrapper.mux.v1.Mux.Stream:input_type -> tlswrapper.mux.v1.Chunk
	4, // 5: tlswrapper.mux.v1.Mux.Control:output_type -> tlswrapper.mux.v1.ControlMessage
	0, // 6: tlswrapper.mux.v1.Mux.Stream:output_type -> tlswrapper.mux.v1.Chunk
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mux_proto_init() }
func file_mux_proto_init() {
	if File_mux_proto != nil {
		return
	}
	file_mux_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlMessage_ClientHello)(nil),
		(*ControlMessage_ServerHello)(nil),
		(*ControlMessage_OpenRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mux_proto_rawDesc), len(file_mux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mux_proto_goTypes,
		DependencyIndexes: file_mux_proto_depIdxs,
		MessageInfos:      file_mux_proto_msgTypes,
	}.Build()
	File_mux_proto = out.File
	file_mux_proto_goTypes = nil
	file_mux_proto_depIdxs = nil
}
