// tlswrapper (c) 2021-2026 He Xian <hexian000@outlook.com>
// This code is licensed under MIT license (see LICENSE for details)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mux.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MuxService_Control_FullMethodName = "/tlswrapper.mux.v1.MuxService/Control"
	MuxService_Stream_FullMethodName  = "/tlswrapper.mux.v1.MuxService/Stream"
)

// MuxServiceClient is the client API for MuxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MuxService provides logical stream multiplexing over one gRPC connection.
//
// Lifecycle:
//  1. Client calls Control; sends Hello; server replies with HelloAck.
//     The control stream stays open for the lifetime of the session.
//  2. Client-initiated streams: client calls Stream directly.
//  3. Server-initiated streams: server sends OpenRequest on Control;
//     client calls Stream with x-mux-request-id metadata set to request_id.
type MuxServiceClient interface {
	// Control is a long-lived bidi stream used for session handshake and
	// server-side stream initiation.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error)
	// Stream is a single logical bidirectional byte stream.
	// Client-initiated: no special metadata required.
	// Server-initiated: client sets x-mux-request-id metadata to the
	// request_id from the OpenRequest message received on Control.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Chunk, Chunk], error)
}

type muxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMuxServiceClient(cc grpc.ClientConnInterface) MuxServiceClient {
	return &muxServiceClient{cc}
}

func (c *muxServiceClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MuxService_ServiceDesc.Streams[0], MuxService_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MuxService_ControlClient = grpc.BidiStreamingClient[ControlMessage, ControlMessage]

func (c *muxServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Chunk, Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MuxService_ServiceDesc.Streams[1], MuxService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, Chunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MuxService_StreamClient = grpc.BidiStreamingClient[Chunk, Chunk]

// MuxServiceServer is the server API for MuxService service.
// All implementations must embed UnimplementedMuxServiceServer
// for forward compatibility.
//
// MuxService provides logical stream multiplexing over one gRPC connection.
//
// Lifecycle:
//  1. Client calls Control; sends Hello; server replies with HelloAck.
//     The control stream stays open for the lifetime of the session.
//  2. Client-initiated streams: client calls Stream directly.
//  3. Server-initiated streams: server sends OpenRequest on Control;
//     client calls Stream with x-mux-request-id metadata set to request_id.
type MuxServiceServer interface {
	// Control is a long-lived bidi stream used for session handshake and
	// server-side stream initiation.
	Control(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error
	// Stream is a single logical bidirectional byte stream.
	// Client-initiated: no special metadata required.
	// Server-initiated: client sets x-mux-request-id metadata to the
	// request_id from the OpenRequest message received on Control.
	Stream(grpc.BidiStreamingServer[Chunk, Chunk]) error
	mustEmbedUnimplementedMuxServiceServer()
}

// UnimplementedMuxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMuxServiceServer struct{}

func (UnimplementedMuxServiceServer) Control(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedMuxServiceServer) Stream(grpc.BidiStreamingServer[Chunk, Chunk]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedMuxServiceServer) mustEmbedUnimplementedMuxServiceServer() {}
func (UnimplementedMuxServiceServer) testEmbeddedByValue()                    {}

// UnsafeMuxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MuxServiceServer will
// result in compilation errors.
type UnsafeMuxServiceServer interface {
	mustEmbedUnimplementedMuxServiceServer()
}

func RegisterMuxServiceServer(s grpc.ServiceRegistrar, srv MuxServiceServer) {
	// If the following call panics, it indicates UnimplementedMuxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MuxService_ServiceDesc, srv)
}

func _MuxService_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MuxServiceServer).Control(&grpc.GenericServerStream[ControlMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MuxService_ControlServer = grpc.BidiStreamingServer[ControlMessage, ControlMessage]

func _MuxService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MuxServiceServer).Stream(&grpc.GenericServerStream[Chunk, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MuxService_StreamServer = grpc.BidiStreamingServer[Chunk, Chunk]

// MuxService_ServiceDesc is the grpc.ServiceDesc for MuxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MuxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tlswrapper.mux.v1.MuxService",
	HandlerType: (*MuxServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _MuxService_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Stream",
			Handler:       _MuxService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mux.proto",
}
