// tlswrapper (c) 2021-2026 He Xian <hexian000@outlook.com>
// This code is licensed under MIT license (see LICENSE for details)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mux.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mux_Control_FullMethodName = "/tlswrapper.mux.v1.Mux/Control"
	Mux_Stream_FullMethodName  = "/tlswrapper.mux.v1.Mux/Stream"
)

// MuxClient is the client API for Mux service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mux provides logical stream multiplexing over one gRPC connection.
//
// Lifecycle:
//  1. Client calls Control; sends ClientHello; server replies with ServerHello.
//     The control stream stays open for the lifetime of the session.
//  2. Client-initiated streams: client calls Stream directly.
//  3. Server-initiated streams: server sends OpenRequest on Control;
//     client calls Stream with x-mux-request-id metadata set to request_id.
type MuxClient interface {
	// Control is a long-lived bidi stream used for session handshake and
	// server-side stream initiation.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error)
	// Stream is a single logical bidirectional byte stream.
	// Client-initiated: no special metadata required.
	// Server-initiated: client sets x-mux-request-id metadata to the
	// request_id from the OpenRequest message received on Control.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Chunk, Chunk], error)
}

type muxClient struct {
	cc grpc.ClientConnInterface
}

func NewMuxClient(cc grpc.ClientConnInterface) MuxClient {
	return &muxClient{cc}
}

func (c *muxClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Mux_ServiceDesc.Streams[0], Mux_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mux_ControlClient = grpc.BidiStreamingClient[ControlMessage, ControlMessage]

func (c *muxClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Chunk, Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Mux_ServiceDesc.Streams[1], Mux_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, Chunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mux_StreamClient = grpc.BidiStreamingClient[Chunk, Chunk]

// MuxServer is the server API for Mux service.
// All implementations must embed UnimplementedMuxServer
// for forward compatibility.
//
// Mux provides logical stream multiplexing over one gRPC connection.
//
// Lifecycle:
//  1. Client calls Control; sends ClientHello; server replies with ServerHello.
//     The control stream stays open for the lifetime of the session.
//  2. Client-initiated streams: client calls Stream directly.
//  3. Server-initiated streams: server sends OpenRequest on Control;
//     client calls Stream with x-mux-request-id metadata set to request_id.
type MuxServer interface {
	// Control is a long-lived bidi stream used for session handshake and
	// server-side stream initiation.
	Control(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error
	// Stream is a single logical bidirectional byte stream.
	// Client-initiated: no special metadata required.
	// Server-initiated: client sets x-mux-request-id metadata to the
	// request_id from the OpenRequest message received on Control.
	Stream(grpc.BidiStreamingServer[Chunk, Chunk]) error
	mustEmbedUnimplementedMuxServer()
}

// UnimplementedMuxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMuxServer struct{}

func (UnimplementedMuxServer) Control(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedMuxServer) Stream(grpc.BidiStreamingServer[Chunk, Chunk]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedMuxServer) mustEmbedUnimplementedMuxServer() {}
func (UnimplementedMuxServer) testEmbeddedByValue()             {}

// UnsafeMuxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MuxServer will
// result in compilation errors.
type UnsafeMuxServer interface {
	mustEmbedUnimplementedMuxServer()
}

func RegisterMuxServer(s grpc.ServiceRegistrar, srv MuxServer) {
	// If the following call panics, it indicates UnimplementedMuxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mux_ServiceDesc, srv)
}

func _Mux_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MuxServer).Control(&grpc.GenericServerStream[ControlMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mux_ControlServer = grpc.BidiStreamingServer[ControlMessage, ControlMessage]

func _Mux_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MuxServer).Stream(&grpc.GenericServerStream[Chunk, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mux_StreamServer = grpc.BidiStreamingServer[Chunk, Chunk]

// Mux_ServiceDesc is the grpc.ServiceDesc for Mux service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mux_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tlswrapper.mux.v1.Mux",
	HandlerType: (*MuxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _Mux_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Stream",
			Handler:       _Mux_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mux.proto",
}
