name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./v2

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Install dependencies
        run: |
          go mod vendor
        working-directory: ${{env.working-directory}}

      - name: Build
        run: go build -v ./...
        working-directory: ${{env.working-directory}}

      - name: Test
        run: go test -v ./...
        working-directory: ${{env.working-directory}}
